version: 2

defaults: &defaults 
  # working_directory: ~/oneapp
  docker:
    - image: circleci/node

  jobs: 
    test:
        <<: *defaults 
        steps:  
          - checkout 

          - run: 
              name: Application Build 
              command: npm install 