version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:15.7.0
       
    steps:
      
      - run: 
          name: update-npm
          command: sudo npm-install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}  

      - run: 
          name: install-npm-wee
          command: npm install

      - save_cache:
            key: dependency-cache-{{ checksum "package.json"}}
            paths:
              - ./node_modules

      - run: 
          name: test 
          command: npm test
      - store_test_results: 
          path: test-results.xml
                


