version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

defaults: &defaults 
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node

#A job is a series of steps that are used 
jobs: 
  build_and_test:
    <<: *defaults 
    steps:  #steps are a set of commands that are ran when running a job
      - checkout 
      - run: 
          name: Build OneApp App 
          command: npm install 
      - run:
          name: Test OneApp App  
          command: npm test 
      
      - persist_to_workspace:
          root: /home/circleci/project
          paths: .
              
#Workflow are the rules used to define a set of jobs.           
workflows:
  oneapp-pkg:
    jobs:
      - build_and_test 
      - heroku/deploy-via-git: 
          api-key: $HEROKU_API_KEY
          app-name: $HEROKU_APP_NAME
          requires:
            - build_and_test
