version: 2

defaults: &defaults 
  docker:
    - image: circleci/node

jobs: 
  test:
    <<: *defaults 
    steps:  
      - checkout 
      - run: 
          name: Application Build 
          command: npm install 
      - run:
          name: Application test  
          command: npm test 

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set Registry URL
          command: npm set registry https://registry.npmjs.org/
      - run:
          name: Authenticate with Registry
          command: echo "//registry.npmjs.org/:_authToken=9f2c0353-050a-46d4-b138-bd546bd14a43"
      - run:
          name: Publish Package to NPM
          command: npm publish
            

workflows:
  version: 2
  oneapp-pkg:
    jobs:
      - test 
      - publish:
           requires:
             - test