version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

defaults: &defaults 
  working_directory: /home/circleci/project
  environment:
    HEROKU_API_KEY: $HEROKU_API_KEY
    HEROKU_APP_NAME: $HEROKU_APP_NAME

#A job is a series of steps that are used 
jobs: 
  build:
    <<: *defaults 
    docker:
      - image: circleci/node
    
    steps:  #steps are a set of commands that are ran when running a job
      - checkout 
      # - run: 
      #     name: Build OneApp App 
      #     command: npm install 
      # - run:
      #     name: Test OneApp App  
      #     command: npm test 
      
      # - persist_to_workspace:
      #     root: /home/circleci/project
      #     paths: .
      - run: echo "Do some stuff with $HEROKU_API_KEY..."
      - heroku/deploy-via-git

#Workflow are the rules used to define a set of jobs.           
workflows:
  oneapp-pkg:
    jobs:
      - build 
      # - pkg_deploy: 
          # requires:
          #   - build

