version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4
  environment: 
    HEROKU_APP_NAME: $HEROKU_APP_NAME
    HEROKU_API_KEY: $HEROKU_API_KEY

defaults: &defaults 
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node


#A job is a series of steps that are used 
jobs: 
  build:
    <<: *defaults 
    steps:  #steps are a set of commands that are ran when running a job
      - checkout 
      - run: 
          name: Build OneApp App 
          command: npm install 
      - run:
          name: Test OneApp App  
          command: npm test 
      
      # - persist_to_workspace:
      #     root: /home/circleci/project
      #     paths: .        


#Workflow are the rules used to define a set of jobs.           
workflows:
  oneapp-pkg:
    jobs:
      - build 
      - heroku/deploy-via-git:
          requires:
            - build
          parameters:
            api-key:
                default: $HEROKU_API_KEY
                description: The name of the environment variable containing your Heroku API Key.
            app-name:
                default: $HEROKU_APP_NAME
                description: The name of your Heroku App. For backwards compatibility the literal value `$HEROKU_APP_NAME` is the default, so you can easily use this command by setting an environment variable called HEROKU_APP_NAME
