version: 2.0

defaults: &defaults 
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node
  environment:
    HEROKU_API_KEY: HEROKU_API_KEY
    HEROKU_APP_NAME: HEROKU_APP_NAME

#A job is a series of steps that are used 
jobs: 
  build:
    <<: *defaults     
    steps:  #steps are a set of commands that are ran when running a job
      - checkout 
      - run: 
          name: Build OneApp App 
          command: npm install 
      - run:
          name: Test OneApp App  
          command: npm test 
      
      - persist_to_workspace:
          root: /home/circleci/project
          paths: .

  deploy:
    <<: *defaults   
    steps:
      - run:
          name: Setup Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

#Workflow are the rules used to define a set of jobs.           
workflows:
  oneapp-pkg:
    jobs:
      - build 
      # - heroku/deploy-via-git: 
      #     requires:
      #       - build

