version: 2

defaults: &defaults 
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node

jobs: 
  test:
    <<: *defaults 
    steps:  
      - checkout 
      - run: 
          name: Application Build 
          command: npm install 
      - run:
          name: Application test  
          command: npm test 
      
      - persist_to_workspace:
          root: /home/circleci/project
          paths: .

  #publish:
    #<<: *defaults
    #steps:
      #- attach_workspace:
      #    at: /home/circleci/project
      # - run:
      #     name: Set Registry URL
      #     command: | 
      #       npm set registry https://registry.npmjs.org/
      #       npm set scope dorimw

      # - run:
      #     name: Authenticate with Registry
      #     command: echo "//registry.npmjs.org/:_authToken=9f2c0353-050a-46d4-b138-bd546bd14a43" > ~/.npmrc
      #- run:
       #   name: Publish Package to NPM
        #  command: |
         #   echo "//registry.npmjs.org/:_authToken=9f2c0353-050a-46d4-b138-bd546bd14a43" > ~/.npmrc
          #  npm login --registry=https://registry.npmjs.org/ --scope=dorimw
           # npm publish --access private
            
    #Using an Heruko Orb to Deploy the App
orbs:
  heroku: circleci/heroku
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: your-database-migration-command
          pre-steps:
            - run: command-that-run-before-deploying
  

workflows:
  version: 2
  oneapp-pkg:
    jobs:
      - test 
      - publish:
           requires:
             - test

